sudo: required
services:
  - docker

before_install:
- docker pull quay.io/pypa/manylinux1_x86_64
- docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd; yum update -y; git clone git://github.com/ecell/ecell4; /opt/python/cp27-cp27mu/bin/python -m pip install cython; /opt/python/cp35-cp35m/bin/python -m pip install cython; /opt/python/cp34-cp34m/bin/python -m pip install cython; yum install cmake gsl-devel -y; wget http://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.14/bin/linux-centos5-x86_64-gcc482/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared.tar.gz; tar xf hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared.tar.gz; tar xf boost_1_59_0.tar.gz; cd /root/ecell4; BOOST_INCLUDEDIR=/root/boost_1_59_0 cmake .; cd /root/ecell4/python; LIBRARY_PATH=/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib CPATH=/root/boost_1_59_0:/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/include /opt/python/cp27-cp27mu/bin/python setup.py bdist_wheel; LIBRARY_PATH=/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib CPATH=/root/boost_1_59_0:/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/include /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel; LIBRARY_PATH=/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib CPATH=/root/boost_1_59_0:/root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/include /opt/python/cp34-cp34m/bin/python setup.py bdist_wheel; cp /root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib/libhdf5.so.9 /lib64/; cp /root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib/libhdf5_cpp.so.9 /lib64/; cp /root/hdf5-1.8.14-linux-centos5-x86_64-gcc482-shared/lib/libsz.so.2 /lib64/; auditwheel repair /root/ecell4/python/dist/ecell-4.0.2-cp35-cp35m-linux_x86_64.whl; auditwheel repair /root/ecell4/python/dist/ecell-4.0.2-cp34-cp34m-linux_x86_64.whl; auditwheel repair /root/ecell4/python/dist/ecell-4.0.2-cp27-cp27mu-linux_x86_64.whl"
- docker cp aaa:/root/ecell4/python/wheelhouse/ecell-4.0.2-cp27-cp27mu-manylinux1_x86_64.whl ./
- docker cp aaa:/root/ecell4/python/wheelhouse/ecell-4.0.2-cp34-cp34m-manylinux1_x86_64.whl ./
- docker cp aaa:/root/ecell4/python/wheelhouse/ecell-4.0.2-cp35-cp35m-manylinux1_x86_64.whl ./

script:
- pwd
- ls -lh

deploy:
  provider: releases
  api_key:
    secure: Oz0EVQ0VDKNhE4k7dr+plJvUZwN6pkfYGOXOKUCRIjtA+MLKx3lY5++83F72nKqF6Y1ud6N7Fu/dAUzslcXZIKJ/fQ25bzRc6FfUEFFkS0DmqZTQY2i1S0s+li8J4u9LGPQndVRUg7Z4IXkcyVnogtnYdmjuwfC1h5njIShiR6LUj9nIC4WpSK1IXrH1IhV0sGxr3WynmYp7H5tbAuZ1hUnG5YQ3T0eOoD6HaNo0kRdnCMPRebJ16YrbZ2rBcHMYu2WQM36awxQfNDyV8w/4iRVL/2knRd9eDXrKkv2TsUcD0ZoSz6iuGwBRxkIZLL9nDJIW+QXM6TJdwTfPKynR/vj/fp+V4wN+vFsvM7mQIVfzhh6hbIbPBdFDtClKz7Tj6ekmDOQvTfC+Auqxzq9Q9lQKEkFxhDNGZvjtze9/2qjktKhD8Hl0oDEcUMeAYRgIk/x1e/Ro7fWJTDPoQW4jPTlhJKCddrXF5+RxyoNqx1VF65bgrSfTSNaqkZvlRQTg9y1xloaiV7jHnNDuZG3NQ2qweDiqEiHro2+KXef7FOtHguPEsnSgqnSkzd50q8eklAZn2elYWRBqLQ0FQFdYxlXGhClxiuiU1zL6JgppDNM1QLUDgCPePlMhJtx/QUVSmfIaGc6r62Z7eMH54ShIZDE0j62GOi+iNUzH0rp+tk0=
  file:
    - "ecell-4.0.2-cp27-cp27mu-manylinux1_x86_64.whl"
    - "ecell-4.0.2-cp34-cp34m-manylinux1_x86_64.whl"
    - "ecell-4.0.2-cp35-cp35m-manylinux1_x86_64.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
