sudo: required
services:
  - docker

env:
  global:
    - VERSION="4.1.1"
    - PY27="cp27-cp27mu"
    - PY35="cp35-cp35m"
    - PY36="cp36-cp36m"

before_install:
- docker pull quay.io/pypa/manylinux1_x86_64
- docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd &&
  git clone -b 'v4.1.1' --single-branch --depth 1 git://github.com/ecell/ecell4 &&
  /opt/python/${PY27}/bin/python -m pip install cython &&
  /opt/python/${PY35}/bin/python -m pip install cython &&
  /opt/python/${PY36}/bin/python -m pip install cython &&
  curl -O https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz &&
  wget ftp://ftp.gnu.org/gnu/gsl/gsl-2.3.tar.gz &&
  wget http://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz &&
  wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2 &&
  tar xf cmake-3.7.2.tar.gz && tar xf gsl-2.3.tar.gz &&
  tar xf hdf5-1.8.17.tar.bz2 && tar xf boost_1_59_0.tar.gz &&
  cd cmake-3.7.2 && ./configure && make && make install &&
  cd ../gsl-2.3 && ./configure && make && make install &&
  cd ../hdf5-1.8.17 && ./configure --prefix=/usr/local --enable-cxx && make && make install &&
  cd /root/ecell4 && export BOOST_INCLUDEDIR=/root/boost_1_59_0 &&
  cmake -DNO_SHARED:BOOL=1 -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/${PY27}/bin/python . &&
  make && auditwheel repair /root/ecell4/python/dist/ecell-${VERSION}-${PY27}-linux_x86_64.whl && rm -f CMakeCache.txt &&
  cmake -DNO_SHARED:BOOL=1 -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/${PY35}/bin/python . &&
  make && auditwheel repair /root/ecell4/python/dist/ecell-${VERSION}-${PY35}-linux_x86_64.whl && rm -f CMakeCache.txt &&
  cmake -DNO_SHARED:BOOL=1 -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/${PY36}/bin/python . &&
  make && auditwheel repair /root/ecell4/python/dist/ecell-${VERSION}-${PY36}-linux_x86_64.whl"
- docker cp aaa:/root/ecell4/wheelhouse/ecell-${VERSION}-${PY27}-manylinux1_x86_64.whl ./
- docker cp aaa:/root/ecell4/wheelhouse/ecell-${VERSION}-${PY35}-manylinux1_x86_64.whl ./
- docker cp aaa:/root/ecell4/wheelhouse/ecell-${VERSION}-${PY36}-manylinux1_x86_64.whl ./

script:
- pwd && ls -lh

deploy:
  provider: releases
  api_key:
    secure: dSmokM/OSM47xxD1ZcrTzbx76XUcQvAY6j/E+tGhONJ2OskHOhqm4RCT/Jct+mE3lUmEEswr9barsfSrn//SziKfi0gjvEGoXJCe5GIcF+ugUiITcHjS8cDDeKTf5FjIs+Cw65aqhJN/SODBbg3qfIdxyPxKNX85IbpOzSNayawglYgTlvRk3W/ZKA+hIBcSXTyfPnV/dmxY9y1wihOKdSoh+YyCQbaG2W6juVmvYL78tk7CP8MDLvbZ6nWf2CptmSK46Ydeb7nVESbLtTP6RrwEIjgNh5cnMb8/wymnOLjBiLDwfmafp565jKVhMP1vd+Vkm/tbNzuYrj6kFzCgi+gwEDwS38Tnv2IxCup7QPMNv2d09Co4EUFQSgZHPQ4ZEbST3L0eLrnBJbylya+qz4H4rH5iD1XFQKEa6W62zA3gaWVUIHsy0ywUbGiPTrGDWcV46oy8KnbENvpHJyc5wBP2SMmAcMpiYcckYg9bPxtd8UCC+aK/xCgN6PGWPhYKxyNFh0+wKsXRpitBk4UR86yj+VlqXvb2TSGZl15sOxL4QEC5v+gvVnhsgMfNmfpg6ROXqJ2UPB7bdjoow+yypfH45VCip/cBtbhCQSxEOXhxuo9up+AvzjVXt/TbeEFL7k+c4Dx6USzDn53n9+2GSamr3rjCFleJILxqr2zjpe0=
  file:
    - "ecell-${VERSION}-${PY27}-manylinux1_x86_64.whl"
    - "ecell-${VERSION}-${PY35}-manylinux1_x86_64.whl"
    - "ecell-${VERSION}-${PY36}-manylinux1_x86_64.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
