sudo: required
language: python
services:
  - docker

env:
  global:
    - TAG="ecell4-manylinux"
    - CONTAINER="build"
    - VERSION="4.0.4"
  matrix:
    include:
      - python: "2.7"
        env: PYVERSION="cp27-cp27mu"
      - python: "3.4"
        env: PYVERSION="cp34-cp34m"
      - python: "3.5"
        env: PYVERSION="cp35-cp35m"

install:
  - docker build --build-arg PYVERSION=${PYVERSION} -t ${TAG} .

script:
  - docker create --name ${CONTAINER} ${TAG} /bin/sh
  - docker cp ${CONTAINER}:/root/ecell4/wheelhouse/ecell-${VERSION}-${PYVERSION}-manylinux1_x86_64.whl ./
  - pip install ecell-${VERSION}-${PYVERSION}-manylinux1_x86_64.whl
  - python -c "import ecell4"

deploy:
  provider: releases
  api_key:
    secure: dSmokM/OSM47xxD1ZcrTzbx76XUcQvAY6j/E+tGhONJ2OskHOhqm4RCT/Jct+mE3lUmEEswr9barsfSrn//SziKfi0gjvEGoXJCe5GIcF+ugUiITcHjS8cDDeKTf5FjIs+Cw65aqhJN/SODBbg3qfIdxyPxKNX85IbpOzSNayawglYgTlvRk3W/ZKA+hIBcSXTyfPnV/dmxY9y1wihOKdSoh+YyCQbaG2W6juVmvYL78tk7CP8MDLvbZ6nWf2CptmSK46Ydeb7nVESbLtTP6RrwEIjgNh5cnMb8/wymnOLjBiLDwfmafp565jKVhMP1vd+Vkm/tbNzuYrj6kFzCgi+gwEDwS38Tnv2IxCup7QPMNv2d09Co4EUFQSgZHPQ4ZEbST3L0eLrnBJbylya+qz4H4rH5iD1XFQKEa6W62zA3gaWVUIHsy0ywUbGiPTrGDWcV46oy8KnbENvpHJyc5wBP2SMmAcMpiYcckYg9bPxtd8UCC+aK/xCgN6PGWPhYKxyNFh0+wKsXRpitBk4UR86yj+VlqXvb2TSGZl15sOxL4QEC5v+gvVnhsgMfNmfpg6ROXqJ2UPB7bdjoow+yypfH45VCip/cBtbhCQSxEOXhxuo9up+AvzjVXt/TbeEFL7k+c4Dx6USzDn53n9+2GSamr3rjCFleJILxqr2zjpe0=
  file:
    - "ecell-${VERSION}-${PYVERSION}-manylinux1_x86_64.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
