sudo: required
services:
  - docker

language: generic
env:
  global:
    - VERSION="4.1.2"
  matrix:
    - PYVER="cp36-cp36m"
    - PYVER="cp35-cp35m"
    - PYVER="cp27-cp27mu"

before_install:
- docker pull quay.io/pypa/manylinux1_x86_64
- docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd && yum install cmake hdf5-devel gsl-devel -y &&
  git clone --recursive -b greens_functions --single-branch --depth 1 git://github.com/kaizu/ecell4 &&
  /opt/python/${PYVER}/bin/python -m pip install cython &&
  wget http://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz &&
  tar xf boost_1_59_0.tar.gz &&
  cd /root/ecell4 && export BOOST_INCLUDEDIR=/root/boost_1_59_0 &&
  cmake -DNO_SHARED:BOOL=1 -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/${PYVER}/bin/python . &&
  make && auditwheel repair /root/ecell4/python/dist/ecell-${VERSION}-${PYVER}-linux_x86_64.whl && rm -f CMakeCache.txt"
- docker cp aaa:/root/ecell4/wheelhouse/ecell-${VERSION}-${PYVER}-manylinux1_x86_64.whl ./

script:
- pwd && ls -lh

deploy:
  provider: releases
  api_key:
    secure: dSmokM/OSM47xxD1ZcrTzbx76XUcQvAY6j/E+tGhONJ2OskHOhqm4RCT/Jct+mE3lUmEEswr9barsfSrn//SziKfi0gjvEGoXJCe5GIcF+ugUiITcHjS8cDDeKTf5FjIs+Cw65aqhJN/SODBbg3qfIdxyPxKNX85IbpOzSNayawglYgTlvRk3W/ZKA+hIBcSXTyfPnV/dmxY9y1wihOKdSoh+YyCQbaG2W6juVmvYL78tk7CP8MDLvbZ6nWf2CptmSK46Ydeb7nVESbLtTP6RrwEIjgNh5cnMb8/wymnOLjBiLDwfmafp565jKVhMP1vd+Vkm/tbNzuYrj6kFzCgi+gwEDwS38Tnv2IxCup7QPMNv2d09Co4EUFQSgZHPQ4ZEbST3L0eLrnBJbylya+qz4H4rH5iD1XFQKEa6W62zA3gaWVUIHsy0ywUbGiPTrGDWcV46oy8KnbENvpHJyc5wBP2SMmAcMpiYcckYg9bPxtd8UCC+aK/xCgN6PGWPhYKxyNFh0+wKsXRpitBk4UR86yj+VlqXvb2TSGZl15sOxL4QEC5v+gvVnhsgMfNmfpg6ROXqJ2UPB7bdjoow+yypfH45VCip/cBtbhCQSxEOXhxuo9up+AvzjVXt/TbeEFL7k+c4Dx6USzDn53n9+2GSamr3rjCFleJILxqr2zjpe0=
  file:
    - "ecell-${VERSION}-${PYVER}-manylinux1_x86_64.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
