version: 2
jobs:
  build:
    working_directory: /root
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout
      - run: cd &&
             git clone --recursive -b greens_functions --single-branch --depth 1 git://github.com/kaizu/ecell4 &&
             /opt/python/cp35-cp35m/bin/python -m pip install cython &&
             curl -O https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz &&
             wget --no-check-certificate ftp://ftp.gnu.org/gnu/gsl/gsl-2.3.tar.gz &&
             wget --no-check-certificate https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2 &&
             wget --no-check-certificate https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2 &&
             tar xf cmake-3.7.2.tar.gz && tar xf gsl-2.3.tar.gz && tar xf hdf5-1.8.17.tar.bz2 && tar xf boost_1_63_0.tar.bz2 &&
             cd cmake-3.7.2 && ./configure && make && make install &&
             cd ../gsl-2.3 && ./configure && make && make install &&
             cd ../hdf5-1.8.17 && ./configure --prefix=/usr/local --enable-cxx && make && make install &&
             cd /root/ecell4 && export BOOST_INCLUDEDIR=/root/boost_1_63_0 &&
             cmake -DNO_SHARED:BOOL=1 -DPYTHON_EXECUTABLE:FILEPATH=/opt/python/cp35-cp35m/bin/python . && make
             
